<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Testing</name>
   <tag></tag>
   <elementGuidId>423813de-ab2c-48bf-b4bd-0ddc7215f460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Production'])[1]/following::label[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8ec0a4fe-4068-413e-b0a8-339b44c7a07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-medium peer-disabled:cursor-not-allowed peer-disabled:opacity-70 text-xs text-gray-500 cursor-pointer select-none</value>
      <webElementGuid>cefe2020-dc3b-4ae4-b07d-c65f9f09730e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>data-source-switch</value>
      <webElementGuid>62657510-af4f-4917-a5f9-8085f888b5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing</value>
      <webElementGuid>febe0f75-5705-4d06-a5bc-71e7b2de213f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;flex h-screen bg-gray-50&quot;]/main[@class=&quot;flex-1 min-w-0 overflow-auto&quot;]/div[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex flex-col min-h-screen bg-gray-50&quot;]/header[@class=&quot;bg-gray-50 px-6 py-4 mb-2&quot;]/div[@class=&quot;flex items-center justify-between&quot;]/div[@class=&quot;flex items-center gap-2&quot;]/div[@class=&quot;flex items-center gap-3&quot;]/div[@class=&quot;flex items-center gap-2&quot;]/label[@class=&quot;font-medium peer-disabled:cursor-not-allowed peer-disabled:opacity-70 text-xs text-gray-500 cursor-pointer select-none&quot;]</value>
      <webElementGuid>6f991621-6cd7-422e-867c-b947da2be6c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Production'])[1]/following::label[1]</value>
      <webElementGuid>25796419-d2e5-4f67-8993-60623d700afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Execution Tracking'])[1]/following::label[2]</value>
      <webElementGuid>c8309c10-9f2b-48d8-8581-f210eab05262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May'])[1]/preceding::label[1]</value>
      <webElementGuid>de445d99-e651-443c-9744-982c44e4221a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load Data'])[1]/preceding::label[1]</value>
      <webElementGuid>09b5e711-3f28-4c48-a2d0-906598ce58d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Testing']/parent::*</value>
      <webElementGuid>fca50afd-7826-41de-97fe-74ebe3d028f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>7122786d-2085-4466-97b7-bdbd835b9e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Testing' or . = 'Testing')]</value>
      <webElementGuid>93fbb9b7-48b3-44e9-bc62-be0a2f8a1bdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
