<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_0_1</name>
   <tag></tag>
   <elementGuidId>51ae6c79-0c33-45ba-911c-9c5d7075ad05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='0%']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#recharts-zindex-2000-_r_1n_ > g.recharts-cartesian-axis-tick-labels.recharts-xAxis-tick-labels > g.recharts-layer.recharts-cartesian-axis-tick-label > text.recharts-text.recharts-cartesian-axis-tick-value > tspan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>d6e45a69-b7a2-4ee7-a1d0-9a2c5046bcb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>449.5</value>
      <webElementGuid>8bd88b39-8ff8-453b-9049-be51a57bc297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0.71em</value>
      <webElementGuid>758ea0f1-0c9c-414a-be5d-125d9f643a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0%</value>
      <webElementGuid>5e19c108-3c02-4c11-88ba-1ac99ea16549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recharts-zindex-2000-_r_1n_&quot;)/g[@class=&quot;recharts-cartesian-axis-tick-labels recharts-xAxis-tick-labels&quot;]/g[@class=&quot;recharts-layer recharts-cartesian-axis-tick-label&quot;]/text[@class=&quot;recharts-text recharts-cartesian-axis-tick-value&quot;]/tspan[1]</value>
      <webElementGuid>165ec1af-f874-4f1a-aa5d-afbb46a65be3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0%']/parent::*</value>
      <webElementGuid>6f49e535-28e5-4563-aebf-2e9c2df1b900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tspan[(text() = '0%' or . = '0%')]</value>
      <webElementGuid>39009598-d8a8-46c0-a70b-ea36e99b6aad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
