<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_0</name>
   <tag></tag>
   <elementGuidId>d73a7079-e133-40b7-8a24-04857660c634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tspan[(text() = '0' or . = '0')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#recharts-zindex-2000-_r_1a_ > g.recharts-cartesian-axis-tick-labels.recharts-xAxis-tick-labels > g.recharts-layer.recharts-cartesian-axis-tick-label > text.recharts-text.recharts-cartesian-axis-tick-value > tspan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>8c2ee6d8-d27d-4720-849e-c4ba018f743e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>208</value>
      <webElementGuid>1bb070ff-ce75-4d6d-9867-fc71fe18612b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0.71em</value>
      <webElementGuid>b7e370ef-fa31-4a8a-bb3b-cbe7ecd6401c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d671a38a-163d-4602-8ba7-6092b3e565b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recharts-zindex-2000-_r_1a_&quot;)/g[@class=&quot;recharts-cartesian-axis-tick-labels recharts-xAxis-tick-labels&quot;]/g[@class=&quot;recharts-layer recharts-cartesian-axis-tick-label&quot;]/text[@class=&quot;recharts-text recharts-cartesian-axis-tick-value&quot;]/tspan[1]</value>
      <webElementGuid>bce98d7c-bdae-4d97-a387-e5564589b421</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tspan[(text() = '0' or . = '0')]</value>
      <webElementGuid>1971e1a9-af57-4061-9255-e1bbedc9ae9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
