<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_28</name>
   <tag></tag>
   <elementGuidId>7c3f086e-c2d7-4d6e-8ffd-4cf9ec8aeab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='28']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>a3894f5f-8c54-48c7-a122-66474d3c3d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>707</value>
      <webElementGuid>893112dc-96c5-4ef3-b717-b3df6d4a91f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>0.71em</value>
      <webElementGuid>fc5b3396-35ae-435b-afcb-adf45504149e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>37fbbf28-54cb-4867-8dad-6ad7906889a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recharts-zindex-2000-_r_1a_&quot;)/g[@class=&quot;recharts-cartesian-axis-tick-labels recharts-xAxis-tick-labels&quot;]/g[@class=&quot;recharts-layer recharts-cartesian-axis-tick-label&quot;]/text[@class=&quot;recharts-text recharts-cartesian-axis-tick-value&quot;]/tspan[1]</value>
      <webElementGuid>866554d4-e538-4b29-991d-402494b19044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='28']/parent::*</value>
      <webElementGuid>c42c3551-2f07-4778-9e68-2999cbaa6aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tspan[(text() = '28' or . = '28')]</value>
      <webElementGuid>f3fa7041-4119-4ee8-8b9f-f952bc9af781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
