<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Campo de contraseña en el formulario de login</description>
   <name>login_password</name>
   <tag></tag>
   <elementGuidId>a1b2c3d4-0002-0002-0002-000000000001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1b2c3d4-0002-0002-0002-000000000001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a1b2c3d4-0002-0002-0002-000000000002</webElementGuid>
   </webElementProperties>
</WebElementEntity>
