CustomKeywords.'TempletPortalKeywords.runAuthenticatedSidebarSequence'([
	caseId: 'TC-SCHEDULERS-SIDEBAR-NAV-002',
	platformLabel: 'Schedulers TEST',
	urlVariableName: 'SCHEDULERS_TEST_URL',
	fallbackUrl: 'https://testing-templet-schedulers.vercel.app/',
	settleSeconds: 2,
	navigationRules: [
		[item: 'Home', settleSeconds: 3, readSeconds: 2],
		[item: 'Tracking', settleSeconds: 3, readSeconds: 2],
		[item: 'Metrics', settleSeconds: 3, readSeconds: 1],
		[item: 'Requests (View)', allowClickOnly: true, settleSeconds: 3],
		[item: 'Resources (View)', allowClickOnly: true, settleSeconds: 3],
		[item: 'Daily', expectedUrlFragments: ['/assign'], settleSeconds: 3],
		[item: 'Review', expectedUrlFragments: ['/review'], settleSeconds: 3],
		[item: 'Collateral', expectedUrlFragments: ['/collateral'], settleSeconds: 3]
	],
	sequenceItems: [
		'Home',
		'Tracking',
		'Metrics',
		'Accounts',
		'Initiatives',
		'Contributors',
		'Contacts',
		'Summary',
		'Requests',
		'Resources',
		'Requests (View)',
		'Resources (View)',
		'One-Off Request',
		'Non-Standard Request',
		'Daily',
		'Review',
		'Collateral',
		'Input',
		'Output',
		'Documentation',
		'Logout'
	],
	homeItem: 'Home',
	logoutItem: 'Logout',
	logoutAllowClickOnly: true,
	logoutSettleSeconds: 3
])
