<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Client</name>
   <tag></tag>
   <elementGuidId>20c86005-0894-470c-b4ed-ba7a496ec4aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.row .form-group:nth-child(1) [for=&quot;inputState&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' row ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-group ') and (position() = 1)]//*[@for = 'inputState']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d183d179-897f-4bff-a68c-75ac682ace42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>inputState</value>
      <webElementGuid>0e52f6c3-8398-4860-bfe9-0531c9a72e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Client</value>
      <webElementGuid>4e918804-ebae-4e27-91c5-0e9200e40ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5899a99753e4527b4965bbcb78a12820</value>
      <webElementGuid>e06eea6f-582f-4f53-b9a5-7804cba40af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' row ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-group ') and (position() = 1)]//*[@for = 'inputState']</value>
      <webElementGuid>fd210ce3-a887-4d68-93f3-5ec86ea85b3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' row ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-group ') and (position() = 1)]//*[@for = 'inputState']</value>
      <webElementGuid>fd15bf40-8cac-4ca8-bbf4-634fd16b9e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Client' or . = 'Client')]</value>
      <webElementGuid>7729de5b-74ec-47d0-b6c7-6a7bf2d2391d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
