<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Initiative</name>
   <tag></tag>
   <elementGuidId>5a5c6449-47a8-46e8-a138-bcca114013d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.row .form-group:nth-child(2) [for=&quot;inputState&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' row ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-group ') and (position() = 2)]//*[@for = 'inputState']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>13937f0d-cb60-4bfe-a950-f67aec6f19dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>inputState</value>
      <webElementGuid>e3ec7eee-64ec-4829-8554-6dcc29f719be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Initiative</value>
      <webElementGuid>76cf6d63-3baa-40e0-92f7-8b7057fb06c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0e07ed3e49681ac310d2411470d4cb32</value>
      <webElementGuid>2c8bc994-4334-492e-8881-2ff5ca782f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' row ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-group ') and (position() = 2)]//*[@for = 'inputState']</value>
      <webElementGuid>fed01a1d-7ff3-400b-a12b-fda2780dfa15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' row ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-group ') and (position() = 2)]//*[@for = 'inputState']</value>
      <webElementGuid>514b96a3-aa08-4e10-9e4c-dc7f01a38aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Initiative' or . = 'Initiative')]</value>
      <webElementGuid>2bda0d56-bef6-48fb-8d1b-a38af22c9be6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
