<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_background</name>
   <tag></tag>
   <elementGuidId>993ff988-75da-4970-92c9-bf3ef470b34f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>rect#background[fill=&quot;none&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//rect[(@id = 'background') and (@fill = 'none')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>78ebecf4-9ea0-4499-ad55-dd62450e6984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>background</value>
      <webElementGuid>f4cacecb-041f-4382-8823-b99cc2605c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>c70930ef-d011-4004-855f-b1978c9c8f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>f810315b-7a94-4e03-bc4a-b44e56595c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>efcff382-5081-4117-be89-4e1f51879335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(3.034 2.793)</value>
      <webElementGuid>2a77297a-e08f-4e7c-ade6-95978731f600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a09715f3-b81f-4cb5-a023-6439d023f786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-015b19d97bd4043bb787c1e52d2e7df1</value>
      <webElementGuid>8c1449c0-3c79-47b1-bbfe-ff58eb94ad19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//rect[(@id = 'background') and (@fill = 'none')]</value>
      <webElementGuid>98fdaaab-a7d3-41de-bcb2-d2a75c517b04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//rect[(@id = 'background') and (@fill = 'none')]</value>
      <webElementGuid>ce6d606b-d38d-4b50-88d6-45f162d37913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//rect[@id = 'background']</value>
      <webElementGuid>7d01dc00-32aa-4a73-85ff-751f32a76008</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
