<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_alex</name>
   <tag></tag>
   <elementGuidId>ca059e51-3ef5-4f11-9e89-e9dddf78969f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3dfacd5f-9647-4978-bd55-db7cb1613004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2.5 py-1 rounded-md text-xs font-medium border transition-colors bg-white text-gray-500 border-gray-200 hover:bg-gray-50</value>
      <webElementGuid>2b5c599c-4d9b-4ed5-9e74-3b522b093c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>alex</value>
      <webElementGuid>206976de-f270-4d16-a2f4-1f44e123c1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;flex h-screen bg-gray-50&quot;]/main[@class=&quot;flex-1 min-w-0 overflow-auto&quot;]/div[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex flex-col min-h-screen bg-gray-50&quot;]/div[@class=&quot;px-6 py-4 flex-1&quot;]/div[@class=&quot;flex justify-between mb-3&quot;]/div[@class=&quot;flex items-center gap-1.5 mb-4 flex-wrap&quot;]/button[@class=&quot;px-2.5 py-1 rounded-md text-xs font-medium border transition-colors bg-white text-gray-500 border-gray-200 hover:bg-gray-50&quot;]</value>
      <webElementGuid>37aaf4e4-c8d9-44de-a749-93a769356bbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::button[1]</value>
      <webElementGuid>c9af3b1a-6722-49ba-bcca-28d93bd6c38b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/following::button[2]</value>
      <webElementGuid>5ddff888-c040-4c8b-81dc-a556e34b627b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='manuel'])[1]/preceding::button[1]</value>
      <webElementGuid>c6c228c0-89bb-4fbf-b854-44aff8b7be0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arturo'])[1]/preceding::button[2]</value>
      <webElementGuid>d0575cf2-5ae1-42a5-9c57-b725174706d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='alex']/parent::*</value>
      <webElementGuid>997a7d8e-c85a-4f8a-9e96-26d7342f5c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/button[2]</value>
      <webElementGuid>428e4909-ad9a-4c9a-b854-971914e588a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'alex' or . = 'alex')]</value>
      <webElementGuid>d543f208-2bf2-4ff6-be9f-19ec68734e7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
