<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_manuel</name>
   <tag></tag>
   <elementGuidId>1b2c1b86-810d-4597-bd32-3ecbc56b3630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='alex'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc2f6578-b195-41f6-8a2b-1634185b7251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2.5 py-1 rounded-md text-xs font-medium border transition-colors bg-white text-gray-500 border-gray-200 hover:bg-gray-50</value>
      <webElementGuid>df40e647-a50c-4b15-b7cc-e954ba684bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>manuel</value>
      <webElementGuid>78949d5a-7ba7-4073-8bad-8bec23dc1a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;flex h-screen bg-gray-50&quot;]/main[@class=&quot;flex-1 min-w-0 overflow-auto&quot;]/div[@class=&quot;bg-gray-50&quot;]/div[@class=&quot;flex flex-col min-h-screen bg-gray-50&quot;]/div[@class=&quot;px-6 py-4 flex-1&quot;]/div[@class=&quot;flex justify-between mb-3&quot;]/div[@class=&quot;flex items-center gap-1.5 mb-4 flex-wrap&quot;]/button[@class=&quot;px-2.5 py-1 rounded-md text-xs font-medium border transition-colors bg-white text-gray-500 border-gray-200 hover:bg-gray-50&quot;]</value>
      <webElementGuid>aef3a05e-d637-4bfd-8174-2ec6ac7ea151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='alex'])[1]/following::button[1]</value>
      <webElementGuid>98983f2d-78c7-4af9-93b5-e5096e00b8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::button[2]</value>
      <webElementGuid>c69e1c9d-85a0-43b3-9d5c-4733f5632c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arturo'])[1]/preceding::button[1]</value>
      <webElementGuid>afbeed01-2202-43d3-a219-25d7f8416dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing stats for'])[1]/preceding::button[2]</value>
      <webElementGuid>fb39ca2a-6d8c-4cd1-bcc1-e42453314a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='manuel']/parent::*</value>
      <webElementGuid>500d8dc3-5185-4286-a6de-51a9ac17de9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/button[3]</value>
      <webElementGuid>c49b9e9a-8ed1-4138-a7c5-86c2c6cb22c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'manuel' or . = 'manuel')]</value>
      <webElementGuid>80225084-0c77-40f3-9efb-510fe7f30e9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
