<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View List</name>
   <tag></tag>
   <elementGuidId>6f1596b7-69e0-4ce7-83b7-f89f1ec6ae85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-view_list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-view_list ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1229dfb2-2fcc-4832-b436-fa9115c64a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tabs-2</value>
      <webElementGuid>3f8fbedc-1f66-4a12-9874-23f0645bd436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab btn-view_list d-inline-block</value>
      <webElementGuid>1386d2c2-8676-47d0-99df-ac09d4e00a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cd5fe33-0f74-48c4-9c10-19cfc78e6fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>9fcf3de6-cb88-4461-9b86-b3363c623feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View List</value>
      <webElementGuid>e9c33d31-22c6-45e3-ac57-0bab44866402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-134fffdb023256a423d24504845c2001</value>
      <webElementGuid>8c0205a6-969d-4e99-b393-d3dc0be1eecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-view_list ')]</value>
      <webElementGuid>0188217a-5404-4b2e-a862-41ac2fa9765d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-view_list ')]</value>
      <webElementGuid>7583e4ad-7caf-46df-a31a-12f87b50034d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tabs-2' and @title = 'View List']</value>
      <webElementGuid>f5528cd9-08f8-474a-8dfb-445f12ecc67c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
