<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Exportar</name>
   <tag></tag>
   <elementGuidId>3b85af20-b90d-4e60-92b5-71f59591b8e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.dropdown.d-inline-block #dropdownMenuButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' dropdown ') and contains(concat(' ', normalize-space(@class), ' '), ' d-inline-block ')]//*[@id = 'dropdownMenuButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b65ca4e-799a-44b6-883a-3ccbe55d99ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary dropdown-toggle</value>
      <webElementGuid>f9659376-fd41-4385-bbeb-b6a130382a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6fefd779-8545-4e7c-8319-2ad56b11e85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownMenuButton</value>
      <webElementGuid>c337142d-4b53-459e-b383-28ddc5af9ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>28601a56-cb38-4030-906b-4993a85300d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7e8515e2-4d39-4dd9-960f-d6c5cecc3547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>113f22c8-3ea6-4838-9f47-2e227ee0f317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Export
                        </value>
      <webElementGuid>92e044dc-0489-4261-9cb8-dd72d3b0f1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-90983d189ef19fcb7088f8f9ffdc7da2</value>
      <webElementGuid>2fb7b70f-cc8e-44e6-9edd-694033730db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' dropdown ') and contains(concat(' ', normalize-space(@class), ' '), ' d-inline-block ')]//*[@id = 'dropdownMenuButton']</value>
      <webElementGuid>98689639-5512-4378-b3c5-49c9009f504f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' dropdown ') and contains(concat(' ', normalize-space(@class), ' '), ' d-inline-block ')]//*[@id = 'dropdownMenuButton']</value>
      <webElementGuid>8e138bb4-4b76-4772-b3b4-7c2372ada702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dropdownMenuButton' and (text() = '
                            Export
                        ' or . = '
                            Export
                        ')]</value>
      <webElementGuid>75bf3abf-378f-4381-b327-23baf9282624</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
